### ISSUE TITLE
How to label each RGB image?

### ISSUE THREAD

**Issue by kcg2015** [malrabeiah/CameraPredictsBeams#1]
Hi, Muhammad, Thanks for this wonderful repo.  I have a question.  For the scenario 'dist_cam', after downloading the senario data from the ViWi website,  how does one detemine (label) the beam index for each RGB image.  I run the data_generator for the downloaded wireless data and have channel data for each of three of base station. The channel data is of the shape ( # subcarriers , 5000).  I have no idea how to use these data to get the beam idx at a given grid location.  Could you kindly elaborate on this? Thanks for you help!

**Comment by malrabeiah** [comment]
My pleasure @kcg2015. 

To get beam indices you need a beamforming codebook. I did not upload the codebook because it’s a design parameter that may differ from one project to another. I could upload the one I used if you want.

Now, once you have a codebook, getting the labels is simple. Every image in the dataset is tagged with the user location ( x-y coordinates). The same goes for the channels generated using the script. You can just match the coordinates of a channel to those of an image and get a channel-image pair. Using the channel you can find the best beamforming vector in the codebook, and the index of that vector is the label.

Please, let me know if this answers your question.

Cheers

**Comment by kcg2015** [comment]
Thanks a lot for your quick response. Could you kindly upload the codebook? That would be very helpful.  
Another question, when you have a channel for a given grid location,  how do you find the beamforming vector?  Do we use Equation (4) of your paper "Millimeter Wave Base Stations with Cameras: Vision Aided Beam and Blockage Prediction"? If so, is the script provided in any of your repo?  Thanks again.
